// src/routes/blog/+page.svelte
<script>
	import { formatDate } from '$lib/utils'

	export let data
</script>


<svelte:head>
	<title>Blog</title>
	<meta name="description" content="Blog" />
</svelte:head>

<div class="blog-home">
	<ul>
		{#each data.posts as post }
			<li class="post">
				<a href={`/blog/${post.slug}`} class="title">{post.title}</a>
				<p class="date">{formatDate(post.date)}</p>
				<p class="description">{post.description}</p>
			</li>
		{/each}
	</ul>
</div>

<style>
	li {
		list-style: none;
	}
</style>

// src/app/blog/page.tsx
import { allPosts, Post } from "contentlayer/generated"
import Head from "next/head";
import Link from "next/link";

const blog = async () => {
  return (
    <div className="blog-home">
      <Head>
        <title>NextJs Content Layer Blog Template</title>
      </Head>
      <ul>
        {allPosts.map((post, i) => (
          <li className="post" key={i}>
            <Link href={post.slug} className="title">{post.title}</Link>
            <p className="date">{post.date}</p>
            <p className="description">{post.description}</p>
          </li>
        ))}
      </ul>
    </div>
	)
}

export default blog
